# Generated by Django 4.2.23 on 2025-06-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='hospital_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
