# Generated by Django 4.2.23 on 2025-07-02 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_patientprofile_hospital_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='recents_patients',
            field=models.ManyToManyField(blank=True, related_name='recent_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
