# Generated by Django 4.2.23 on 2025-07-07 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_hospital_recents_patients'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patients', to='users.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
