# Generated by Django 4.2.23 on 2025-07-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_diagnosisvisit_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosiscase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
