# Generated by Django 4.2.23 on 2025-07-16 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_hospital_recents_patients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0004_diagnosiscase_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('visit_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_visits', to='medical.diagnosiscase')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_patients', to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
