# Generated by Django 5.2.8 on 2025-11-13 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_scheduledvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='diagnosis_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='medical.diagnosisvisit')),
            ],
        ),
    ]
