# Generated by Django 5.2.8 on 2025-11-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_visitdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitdocument',
            name='file',
        ),
        migrations.AddField(
            model_name='visitdocument',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
